class Specification < ActiveRecord::Base
  validates :version, presence: true, uniqueness: { scope: :title}
  validates :title, presence: true
  has_many :definitions, dependent: :destroy
  has_many :paths, dependent: :destroy

  def display_name
    "#{title} #{version}"
  end

  def load_rc_paths!
    data = %{
      /restapi
      /restapi/{version}
      /restapi/{version}/account
      /restapi/{version}/account/{id}
      /restapi/{version}/account/{id}
      /restapi/{version}/account/{id}
      /restapi/{version}/account/{id}/service-info
      /restapi/{version}/account/~/active-calls
      /restapi/{version}/account/~/business-address
      /restapi/{version}/account/~/business-address
      /restapi/{version}/account/~/call-log
      /restapi/{version}/account/~/call-log
      /restapi/{version}/account/~/call-log/{id}
      /restapi/{version}/account/~/call-log/{id}
      /restapi/{version}/account/~/department/{id}/members
      /restapi/{version}/account/~/device
      /restapi/{version}/account/~/device/{id}
      /restapi/{version}/account/~/device/{id}
      /restapi/{version}/account/~/device/sip-info
      /restapi/{version}/account/~/dialing-plan
      /restapi/{version}/account/~/extension
      /restapi/{version}/account/~/extension
      /restapi/{version}/account/~/extension/{id}
      /restapi/{version}/account/~/extension/{id}
      /restapi/{version}/account/~/extension/{id}
      /restapi/{version}/account/~/extension/{id}/permissions
      /restapi/{version}/account/~/extension/~/active-calls
      /restapi/{version}/account/~/extension/~/address-book-sync
      /restapi/{version}/account/~/extension/~/address-book/contact
      /restapi/{version}/account/~/extension/~/address-book/contact
      /restapi/{version}/account/~/extension/~/address-book/contact/{id}
      /restapi/{version}/account/~/extension/~/address-book/contact/{id}
      /restapi/{version}/account/~/extension/~/address-book/contact/{id}
      /restapi/{version}/account/~/extension/~/address-book/group
      /restapi/{version}/account/~/extension/~/address-book/group
      /restapi/{version}/account/~/extension/~/address-book/group/{id}
      /restapi/{version}/account/~/extension/~/address-book/group/{id}
      /restapi/{version}/account/~/extension/~/address-book/group/{id}
      /restapi/{version}/account/~/extension/~/answering-rule/{id}
      /restapi/{version}/account/~/extension/~/answering-rule/after-hours-rule
      /restapi/{version}/account/~/extension/~/answering-rule/business-hours-rule
      /restapi/{version}/account/~/extension/~/assigned-role
      /restapi/{version}/account/~/extension/~/assigned-role
      /restapi/{version}/account/~/extension/~/authz-profile
      /restapi/{version}/account/~/extension/~/authz-profile/check
      /restapi/{version}/account/~/extension/~/blocked-number
      /restapi/{version}/account/~/extension/~/blocked-number
      /restapi/{version}/account/~/extension/~/blocked-number/{id}
      /restapi/{version}/account/~/extension/~/blocked-number/{id}
      /restapi/{version}/account/~/extension/~/blocked-number/{id}
      /restapi/{version}/account/~/extension/~/business-hours
      /restapi/{version}/account/~/extension/~/call-log
      /restapi/{version}/account/~/extension/~/call-log
      /restapi/{version}/account/~/extension/~/call-log-sync
      /restapi/{version}/account/~/extension/~/call-log/{id}
      /restapi/{version}/account/~/extension/~/call-log/{id}
      /restapi/{version}/account/~/extension/~/company-pager
      /restapi/{version}/account/~/extension/~/company-pager
      /restapi/{version}/account/~/extension/~/company-pager/{id}
      /restapi/{version}/account/~/extension/~/conferencing
      /restapi/{version}/account/~/extension/~/conferencing
      /restapi/{version}/account/~/extension/~/device
      /restapi/{version}/account/~/extension/~/fax
      /restapi/{version}/account/~/extension/~/fax
      /restapi/{version}/account/~/extension/~/fax/{id}
      /restapi/{version}/account/~/extension/~/forwarding-number
      /restapi/{version}/account/~/extension/~/forwarding-number
      /restapi/{version}/account/~/extension/~/grant
      /restapi/{version}/account/~/extension/~/message-store
      /restapi/{version}/account/~/extension/~/message-store/{id}
      /restapi/{version}/account/~/extension/~/message-store/{id}
      /restapi/{version}/account/~/extension/~/message-store/{id}
      /restapi/{version}/account/~/extension/~/message-store/{id}/content/{id}
      /restapi/{version}/account/~/extension/~/message-sync
      /restapi/{version}/account/~/extension/~/phone-number
      /restapi/{version}/account/~/extension/~/presence
      /restapi/{version}/account/~/extension/~/presence
      /restapi/{version}/account/~/extension/~/presence/line
      /restapi/{version}/account/~/extension/~/presence/line
      /restapi/{version}/account/~/extension/~/presence/line/{id}
      /restapi/{version}/account/~/extension/~/presence/permission
      /restapi/{version}/account/~/extension/~/profile-image
      /restapi/{version}/account/~/extension/~/profile-image
      /restapi/{version}/account/~/extension/~/profile-image
      /restapi/{version}/account/~/extension/~/profile-image/195x195
      /restapi/{version}/account/~/extension/~/profile-image/584x584
      /restapi/{version}/account/~/extension/~/profile-image/90x90
      /restapi/{version}/account/~/extension/~/reporting/settings
      /restapi/{version}/account/~/extension/~/reporting/settings
      /restapi/{version}/account/~/extension/~/ringout
      /restapi/{version}/account/~/extension/~/ringout/{id}
      /restapi/{version}/account/~/extension/~/ringout/{id}
      /restapi/{version}/account/~/extension/~/ringout/direct
      /restapi/{version}/account/~/extension/~/sms
      /restapi/{version}/account/~/extension/~/sms
      /restapi/{version}/account/~/extension/~/sms/{id}
      /restapi/{version}/account/~/extension/bulk-assign
      /restapi/{version}/account/~/extension/validate
      /restapi/{version}/account/~/order
      /restapi/{version}/account/~/order/{id}
      /restapi/{version}/account/~/payment-info
      /restapi/{version}/account/~/payment-info
      /restapi/{version}/account/~/phone-number
      /restapi/{version}/account/~/phone-number
      /restapi/{version}/account/~/phone-number/{id}
      /restapi/{version}/account/~/phone-number/{id}
      /restapi/{version}/account/~/phone-number/{id}
      /restapi/{version}/account/~/presence
      /restapi/{version}/account/~/recording/{id}
      /restapi/{version}/account/~/recording/{id}/content
      /restapi/{version}/account/~/user-group
      /restapi/{version}/account/~/user-group
      /restapi/{version}/account/~/user-group/{id}
      /restapi/{version}/account/~/user-group/{id}
      /restapi/{version}/account/~/user-group/{id}
      /restapi/{version}/account/~/user-group/{id}/members
      /restapi/{version}/account/~/user-group/bulk-assign
      /restapi/{version}/account/~/user-role
      /restapi/{version}/account/~/verification-call
      /restapi/{version}/account/~/verification-call/{id}
      /restapi/{version}/account/~/verification-call/{id}
      /restapi/{version}/account/~/verification-call/{id}
      /restapi/{version}/account/validate
      /restapi/{version}/client-info
      /restapi/{version}/client-info/custom-data/{key}
      /restapi/{version}/client-info/custom-data/{key}
      /restapi/{version}/client-info/sip-provision
      /restapi/{version}/client-info/special-number-rule
      /restapi/{version}/dictionary/brand/{id}
      /restapi/{version}/dictionary/country
      /restapi/{version}/dictionary/country/{id}
      /restapi/{version}/dictionary/device
      /restapi/{version}/dictionary/forms/address
      /restapi/{version}/dictionary/language
      /restapi/{version}/dictionary/language/{id}
      /restapi/{version}/dictionary/location
      /restapi/{version}/dictionary/permission
      /restapi/{version}/dictionary/permission-category
      /restapi/{version}/dictionary/secret-question
      /restapi/{version}/dictionary/secret-question/{id}
      /restapi/{version}/dictionary/service-plan/{id}
      /restapi/{version}/dictionary/shipping-options
      /restapi/{version}/dictionary/state
      /restapi/{version}/dictionary/state/{id}
      /restapi/{version}/dictionary/timezone
      /restapi/{version}/dictionary/timezone/{id}
      /restapi/{version}/dictionary/user-role
      /restapi/{version}/internal/address-book
      /restapi/{version}/internal/device-order/update
      /restapi/{version}/internal/message-notification/transcription-result
      /restapi/{version}/internal/number-porting/update-order
      /restapi/{version}/internal/oauth/app-info
      /restapi/{version}/internal/oauth/app-session
      /restapi/{version}/internal/oauth/generate-code
      /restapi/{version}/internal/presence
      /restapi/{version}/internal/presence
      /restapi/{version}/internal/rendering-queue/poll
      /restapi/{version}/internal/rendering-queue/save
      /restapi/{version}/internal/rendering-queue/touch
      /restapi/{version}/internal/send-email
      /restapi/{version}/internal/send-sms
      /restapi/{version}/internal/service-parameter
      /restapi/{version}/internal/service-parameter
      /restapi/{version}/interop/generate-code
      /restapi/{version}/number-parser/parse
      /restapi/{version}/number-parser/phonedata.xml
      /restapi/{version}/number-pool/lookup
      /restapi/{version}/number-pool/reserve
      /restapi/{version}/subscription
      /restapi/{version}/subscription/{id}
      /restapi/{version}/subscription/{id}
      /restapi/{version}/subscription/{id}
      /restapi/auth
      /restapi/oauth/authorize
      /restapi/oauth/revoke
      /restapi/oauth/token
      /sms-inbound/message
      /sms-inbound/receipt
    }.gsub('/{version}', '/v1.0')
     .gsub(%r</([^/]+)/(?:~|\{id\})>){ |m| "/#{$1}/{#{$1.gsub('-', '_').camelize(:lower)}Id}" }
     .gsub(%r</([^/]+)/\{key\}>){ |m| "/#{$1}/{#{$1.gsub('-', '_').camelize(:lower)}Key}" }
    data.split(/\s+/).collect(&:strip).reject{ |line| line == '' }.uniq.each do |line|
      path = self.paths.build(uri: line)
      path.save!
    end
  end
end
